version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9   # or node/java if you need
    commands:
      - echo Installing Apache HTTP Server...
      - yum update -y
      - yum install -y httpd
      - systemctl enable httpd
      - systemctl start httpd

  pre_build:
    commands:
      - echo Pre-build phase complete

  build:
    commands:
      - echo Build started on `date`
      # You can add code compilation or other tasks here

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
